name: chronic_pain_headache
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  dots_indicator: ^2.1.0
  flutter_form_bloc: ^0.30.1
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  responsive_framework: ^0.2.0
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.4.0
  keyboard_dismisser: ^3.0.0
  flutter_animated_dialog: ^2.0.1
  dropdown_search: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - images/
    - fonts/

  fonts:
    - family: Oswald
      fonts: 
        - asset: fonts/Oswald-Bold.ttf
        - asset: fonts/Oswald-ExtraLight.ttf
        - asset: fonts/Oswald-Light.ttf
        - asset: fonts/Oswald-Medium.ttf
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-SemiBold.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
