// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(apiKey: '', appId: '', messagingSenderId: '', projectId: '');
      case TargetPlatform.iOS:
        return const FirebaseOptions(apiKey: '', appId: '', messagingSenderId: '', projectId: '');
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAAKoZH_KNGqpBOIJ0u1hxQHaILq2krt_I",
      authDomain: "chronic-pain-headache.firebaseapp.com",
      projectId: "chronic-pain-headache",
      storageBucket: "chronic-pain-headache.appspot.com",
      messagingSenderId: "786988252274",
      appId: "1:786988252274:web:d679834d362fd3a5ba96eb",
      measurementId: "G-Z8VDKXV20L"
  );

  /*static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1MXTtBFHdQH2s3OdnJDXVZpcLXEOJ_I',
    appId: '1:904331017281:android:d0b7420c0d1a1034301ac0',
    messagingSenderId: '904331017281',
    projectId: 'reactiontest-1f774',
    storageBucket: 'reactiontest-1f774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_HkAq9XR-uDKVpvgCacS3pBO_vgAE8E',
    appId: '1:904331017281:ios:e918fb30f69b3eef301ac0',
    messagingSenderId: '904331017281',
    projectId: 'reactiontest-1f774',
    storageBucket: 'reactiontest-1f774.appspot.com',
    iosClientId: '904331017281-98580nfvjjrk1u4s3nvdfuoq5c8vl93t.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );*/
}
